/**
 * Enumeration for school form accordion items.
 */
const SCHOOL_FORM_ACCORDION_ITEMS = Object.freeze({
  ORGANIZATION: "ORGANIZATION",
  ORGANIZATION_MEMBERS: "ORGANIZATION_MEMBERS",
  SCHOOL: "SCHOOL",
  SCHOOL_ADDRESSES: "SCHOOL_ADDRESSES",
  SCHOOL_ADMINS: "SCHOOL_ADMINS",
});

export { SCHOOL_FORM_ACCORDION_ITEMS };